# Generated by Django 5.2 on 2025-04-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
